=== 20150723/gdm/gui/greeter/greeter.dtd
<!-- dtd for greeter -->

<!ENTITY % colorattrs
	"file CDATA #IMPLIED
	color CDATA #IMPLIED
	font CDATA #IMPLIED
	tint CDATA #IMPLIED"
>

<!ELEMENT greeter (item+)>
<!ELEMENT item (pos,normal?,active?,prelight?,children?)>
<!ELEMENT children (item+)>
<!ELEMENT pos EMPTY>
<!ELEMENT text EMPTY>
<!ELEMENT normal EMPTY>
<!ELEMENT active EMPTY>
<!ELEMENT prelight EMPTY>

<!ATTLIST item
 	type CDATA #REQUIRED
	id CDATA #IMPLIED
>

<!ATTLIST pos
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	anchor CDATA "c"
	width CDATA #IMPLIED
	height CDATA #IMPLIED
>

<!ATTLIST normal
	%colorattrs;
>
<!ATTLIST active
	%colorattrs;
>
<!ATTLIST prelight
	%colorattrs;
>

=== 20150723/gdm/gui/greeter/themes/circles/circles.xml
<?xml version="1.0"?>
<!DOCTYPE greeter SYSTEM "greeter.dtd">
<greeter>
  <item type="svg">
    <normal file="background.svg"/>
    <pos x="0" y="0" width="100%" height="-75"/>
  </item>
  <item type="rect">
    <normal color="#000000"/>
    <pos x="0" y="-75" width="100%" height="75"/>
    <fixed>
      <item type="rect">
        <normal color="#ffffff"/>
        <pos x="0" y="4" width="100%" height="100%"/>
        <box orientation="horizontal" spacing="10" xpadding="10">
	  <item type="pixmap" id="language_button">
	    <normal file="options.png" tint="#dddddd"/>
	    <prelight file="options.png"/>
	    <active file="options.png" tint="#ff0000"/>
	    <pos y="50%" anchor="w"/>
	  </item>
	  <item type="label">
	    <normal color="#000000" font="Sans 14"/>
	    <pos y="50%" anchor="w"/>
	    <text val="Option"/>
	  </item>
	  <item type="pixmap">
	    <normal file="help.png" tint="#dddddd"/>
	    <prelight file="help.png"/>
	    <active file="help.png" tint="#ff0000"/>
	    <pos y="50%" anchor="w"/>
	  </item>
	  <item type="label">
	    <normal color="#000000" font="Sans 14"/>
	    <pos y="50%" anchor="w"/>
	    <text val="Help"/>
	  </item>
        </box>
      </item>
    </fixed>
  </item>
  <item type="pixmap">
    <normal file="flower.png"/>
    <pos x="100%" y="100%" anchor="se"/>
  </item>
  <item type="label" id="clock">
    <normal color="#000000" font="Sans 16"/>
    <pos x="-20" y="-37" anchor="e"/>
    <text val="%c"/>
  </item>

  <item type="rect" id="caps-lock-warning">
    <normal color="#FFFFFF" alpha="0.5"/>
    <pos anchor="c" x="50%" y="75%" width="40%" height="5%"/>
    <fixed>
      <item type="label">
        <normal color="#000000" font="Sans 14"/>
        <pos x="66" y="50%" anchor="w"/>
        <text val="You've got capslock on!"/>
      </item>
    </fixed>
  </item>
  <item type="rect">
    <normal color="#FFFFFF" alpha="0.5"/>
    <pos anchor="c" x="50%" y="50%" width="box" height="box"/>
    <box orientation="vertical" min-width="300" xpadding="30" ypadding="30" spacing="10">
      <item type="label">
        <pos anchor="n" x="50%"/>
        <normal color="#000000" font="Sans 18"/>
	<text val="Welcome to %h"/>
	<text lang="sv" val="VÃ¤lkommen till %h"/>
      </item>
      <item type="label" id="pam-conversation">
        <pos anchor="n" x="50%"/>
        <normal color="#000000" font="Sans 16"/>
	<text val="Please enter your user name"/>
      </item>
      <item type="rect">
	<normal color="#000000"/>
        <pos anchor="n" x="50%" height="24" width="80%"/>
	<fixed>
	  <item type="entry" id="user-pw-entry">
            <pos anchor="nw" x="1" y="1" height="-2" width="-2"/>
	  </item>
	</fixed>
      </item>
    </box>
  </item>
</greeter>
